### ISSUE TITLE
yace format cannot be read by python

### ISSUE THREAD

**Issue by bernstei** [ACEsuit/ACE.jl#102] opened 2022-01-10 14:17 UTC
The default YAML reader (PyYAML?) cannot read yace format potentials as currently written, because they can include dictionaries that have lists as keys, while python only supports tuples as keys.  Here's an example of a format that's produced, problem is on line 7.  

This is really a big deal, since it's just meant to be read by the LAMMPS PACE package, but it would be convenient if a mutually understandable format could be used, so feel free to close it if it's not easy to solve.
```
deltaSplineBins: 0.001
E0:
  - -0.0046603
  - 0.0
  - 0.0
bonds:
  [0, 0]:
    rcut: 3.6
    xl: 0.37051039697542537
    recursion_coefficients:
      B:
        - 0.0
        - -5.913670422702299
        - -4.767753518631563
        - -4.334321380574182
        - -4.1097011882705266
        - -3.974709174650009
      A:
        - 31.295482159646728
        - 7.009373160773004
        - 5.651137307615811
        - 5.137397552378055
        - 4.871159051622799
        - 4.711155309520793
      C:
        - 0.0
        - 0.0
        - -0.8062257748298575
        - -0.9090909090909122
        - -0.9481763873555094
        - -0.9671528397232746
    pl: 2
    radbasename: "ACE.jl.base"
    r0: 1.8
    xr: 1.3168503090567045
    maxn: 6
    pr: 2
    p: 2
```

**Comment by casv2** [comment] 2022-01-10 14:38
> This is really a big deal

Is or isn't? As you say the exported potentials are really only designed to be used with the PACE calculator.

The PACE potentials are read using the C YAML library and used as a PACE evaluator (written by the Drautz group). Our exported ACE potentials should be identical in structure to Drautz' ACE potentials, and both theirs and ours should be read as PACE/LAMMPS evaluators without any problems. I don't think anyone has every tried importing them inside Python. 

That being said, the PACE export function is a big hack indeed... We've had to reformulate the ACE basis in their language which was a bit of a pain and feels hacky...

**Comment by bernstei** [comment] 2022-01-10 14:39
Sorry, typo - supposed to be "isn't".

**Comment by bernstei** [comment] 2022-01-10 14:40
Anyway, I was just trying to use `yaml.safe_load()` as a way of testing the validity of the file created as part of my ACE fitting `wfl` wrapper, but that's hardly essential.  It's pretty hard to come up with a situation where the yace file is written but does not contain valid content.

**Comment by casv2** [comment] 2022-01-10 14:48
Perhaps easiest would be to perform a unit test? Evaluate the potential on a few isolated atoms and see whether the E0's agree. Or maybe just look for the E0's by reading the .yaml as text and check whether they match the provided E0's by the user.

**Comment by bernstei** [comment] 2022-01-10 14:51
It's not a big deal - it was just meant as a sanity check, mostly for situations where e.g. the script got killed while writing.

I guess if it's possible to create an ASE Calculator from a yace I could do that and make sure it doesn't fail.  Right now for json output I just parse it, not actually try to create a Calculator.

**Comment by cortner** [comment] 2022-01-10 15:29
It’s not an immediate problem but so think it is a problem. Does this concern Only OUR ace files or Ralf’s group’s files as well?

**Comment by casv2** [comment] 2022-01-10 16:06
> Does this concern Only OUR ace files or Ralf’s group’s files as well?

Both, Yury has shaped the ACE .yamls this way and both our files are read by the C interface without problems. Apparently trying to read them into Python causes problems...? Weird I know, but I think it's because as mentioned previously:

> python only supports tuples as keys

This is not a problem for the PACE / LAMMPs evaluator since it doesn't use Python.

**Comment by cortner** [comment] 2022-01-10 16:11
Yes but if we want an ecosystem then that’s bad.

**Comment by bernstei** [comment] 2022-01-10 16:14
Note that there's currently no python code that does anything _useful_ with yace files, as far as I know.  It would only be useful as a minimal check on the format of the file being valid yaml.  Supposedly ruamel's python YAML reader can supposedly read such yaml files, and automatically convert the lists to tuples, or somethingng.

 Out of curiosity, can you create a _Julia_ ACE (never mind an ASE `Calculator`) from a yace file?

**Comment by casv2** [comment] 2022-01-10 16:18
No we currently we don't have an option to create a Julia ACE from a .yace file. I'm not sure it would be used much actually, but from an ecosystem perspective it would be nice to have indeed...

**Comment by bernstei** [comment] 2022-01-10 16:19
> I'm not sure it would be used much actually,

I agree - it was just a thought, as an alternative for my consistency check use-case.

**Comment by cortner** [comment] 2022-01-11 23:27
Hm ... let's keep in mind that YACE is really not our format. In fact I don't like it anyway and don't think it is particularly useful for supporting the eco-system. So I will take the point and keep this in mind when we continue discussions with Ralf's group about sharing codes and models, but I just don't think this is an ACE.jl issue. We should think of YACE simply as an export to the PACE code and nothing else. 

Are you both happy with that response and happy to close this issue?

**Comment by bernstei** [comment] 2022-01-11 23:29
> On Jan 11, 2022, at 6:27 PM, Christoph Ortner ***@***.***> wrote:
> 
> 
> Hm ... let's keep in mind that YACE is really not our format. In fact I don't like it anyway and don't think it is particularly useful for supporting the eco-system. So I will take the point and keep this in mind when we continue discussions with Ralf's group about sharing codes and models, but I just don't think this is an ACE.jl issue. We should think of YACE simply as an export to the PACE code and nothing else.
> 
> Are you both happy with that response and happy to close this issue?
> 
I'm certainly happy for you not to support yace beyond writing some version of it that works with lammps (although I think it _is_ really important to support LAMMPS, and preferably without explicit involvement of julia at runtime).

**Comment by cortner** [comment] 2022-01-11 23:31
That will be incredibly difficult to achieve long-term. We are very well aware of the issue, but Julia has such a rich type system that will be difficult to reproduce in a statically compiled code and the more complex the models become the more difficult it will be to support Lammps with a simple static library that doesn't call Julia.

**Comment by cortner** [comment] 2022-01-11 23:31
but this is a much longer and much more difficult discussion for another day.

**Closed by cortner** 2022-01-11 23:32 UTC
