### ISSUE TITLE
Fix and generalise the function `norm(X::XState)`

### ISSUE THREAD

**Issue by zhanglw0521** [ACEsuit/ACE.jl#66] opened 2021-10-21 21:30 UTC
There seems to be a typo in `norm(X::XState)` associated with which the MWE looks like:

```julia
julia> Xs = PositionState([1.0,1.0,1.0])

julia> @show norm(Xs)
norm(Xs) = 2.9999999999999996

julia> @show norm(Xs.rr)
norm(Xs.rr) = 1.7320508075688772
```

and also it won't work for States that have non-number fields, e.g.,

```julia
julia> X = ACE.State(rr = [1.0,1.0,1.0], be = :env);
julia> norm(X)

ERROR: MethodError: no method matching iterate(::Symbol)
```

(A very similar issue occurs in `scaling(basis::PIBasis)` I guess?)

**Comment by cortner** [comment] 2021-12-28 00:00
@zhanglw0521  -- I think this is intended behaviour. I don't see how you can take the norm of this object. Analogy to elementary geometry might help. In geometry you have points and vectors. a point doesn't have a norm. but a vector is pointing from one point to another and it does have a norm - i.e. a well-defined length. 

I'm happy with this behaviour, but if you disagree we can discuss further.

**Comment by zhanglw0521** [comment] 2021-12-28 00:33
Thanks! I would consider all those things are fixed - the first one is indeed fixed with the latest version and as for the second one, I arose those comments simply because: (i) I wanted to add a test to `OffsiteBasis`, i.e., to check do I have a correct cutoff for it but of course I could use `norm(X.rr)` instead of `norm(X)`; (ii) We didn't enable `scaling()` for a basis that has a component `CatagoricalBasis` at that stage but this is also fixed now. I really think we can close this issue, or may I close it now :)?

**Comment by cortner** [comment] 2021-12-28 00:37
Yes, please close it.

**Closed** 2021-12-28 00:38 UTC
